version: '3.8'

services:
  llm-aggregator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/model_memory.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  streamlit:
    build: .
    command: streamlit run web_ui.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - AGGREGATOR_URL=http://llm-aggregator:8000
    depends_on:
      - llm-aggregator
    restart: unless-stopped

volumes:
  redis_data:
